### ISSUE TITLE
Jest testing async redux-thunk actions results in "actions may not have undefined type property"

### ISSUE THREAD

**Issue by goodbomb** [reduxjs/redux-mock-store#127]
HI, I've tried to follow the [official documentation](https://redux.js.org/docs/recipes/WritingTests.html#async-action-creators) for testing Async Action Creators with Redux-Thunk, but I can't seem to get around this error:

```
Actions may not have an undefined "type" property. Have you misspelled a constant? Action: {}

      37 |             }
      38 |         };
    > 39 | 
      40 |         fetchMock.getOnce('/api/orgs/1/projects/2/test_classes/3?version=1.0.0', payload.data);
      41 | 
      42 |         const expectedActions = [

      at dispatch (node_modules/redux-mock-store/lib/index.js:39:19)
      at node_modules/redux-thunk/lib/index.js:14:16
      at dispatch (node_modules/redux/lib/applyMiddleware.js:45:18)
      at src/app/projects/test-classes/ProjectTestClassActions.js:57:9
      at Object.dispatch (node_modules/redux-thunk/lib/index.js:11:18)
      at Object.<anonymous> (src/__tests__/projects/test-classes/ProjectTestClassActions.spec.js:48:22)
```

This is what I've got going on in my test:

```
import { ProjectTestClassActions } from 'app/projects/test-classes';
import * as actions from 'app/projects/test-classes/ProjectTestClassActions';
import fetchMock from 'fetch-mock';
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';

const middlewares = [thunk];
const mockStore = configureMockStore(middlewares);

describe('ProjectTestClassActions -> fetchProjectTestClass()', () => {
    afterEach(() => {
        fetchMock.reset();
        fetchMock.restore();
    });

    it('should create FETCH_PROJECT_TEST_CLASS_SUCCESS action when fetching a test class succeeds', () => {
        const payload = {
            data: {
                name: 'TestClass'
            }
        };

        fetchMock.getOnce('/api/orgs/1/projects/2/test_classes/3', payload.data);

        const expectedActions = [
            { type: ProjectTestClassActions.SEND_REQUEST },
            { type: ProjectTestClassActions.FETCH_PROJECT_TEST_CLASS_SUCCESS, payload }
        ];
        const store = mockStore({ currentTestClass: null });

        return store.dispatch(actions.fetchProjectTestClass(1, 2, 3)).then(() => {
            expect(store.getActions()).toEqual(expectedActions);
        });
    });
});
```

The types in the expectedActions array definitely return values (they're not undefined). Some insight would be greatly appreciated.

**Comment by goodbomb** [comment]
Never mind. Looks like the issue wasn't with the test, but with how I wrote my action creators.

I had this:

```
export const fetchProjectTestClass = (orgId, projectId, testClassId) => {
    const request = ProjectTestClassService.fetchProjectTestClass(orgId, projectId, testClassId);

    return function(dispatch) {
        dispatch(sendRequest(ProjectTestClassActions.SEND_REQUEST));

        dispatch(request.then(
            data => fetchProjectTestClassSuccess(data),
            error => requestFailedRedirect(error, ProjectTestClassActions.REQUEST_FAIL)
        ));
    };
};
```

But it needed to be this:

```
export const fetchProjectTestClass = (orgId, projectId, testClassId) => {
    const request = ProjectTestClassService.fetchProjectTestClass(orgId, projectId, testClassId);

    return function(dispatch) {
        dispatch(sendRequest(ProjectTestClassActions.SEND_REQUEST));

        return request.then(
            data => dispatch(fetchProjectTestClassSuccess(data)),
            error => dispatch(requestFailedRedirect(error, ProjectTestClassActions.REQUEST_FAIL))
        );
    };
};
```
