### ISSUE TITLE
Thunk middleware not working when using mock store in a shallow rendered component

### ISSUE THREAD

**Issue by pendar747** [reduxjs/redux-mock-store#160]
I'm having an issue with the thunk middleware not working when I use the mock store through enzyme
example:
```js
const mapDispatchToProps = dispatch => ({
  register: data => dispatch(register(data))
    .then(() => dispatch(login({
      username: data.email,
      password: data.password
    }))),
  redirectToAccountPage: () => dispatch(push('/my-account'))
});

// my test
register.default.callsFake((data) => {
  expect(data).toMatchSnapshot();
  done();
  return dispatch => dispatch(Promise.resolve({ type: 'register' }));
});
component.find('[name="lastName"]')
  .simulate("change", { target: { value: "Freddy", name: 'lastName' }})
component.find('[name="firstName"]')
  .simulate("change", { target: { value: "Fredo", name: 'firstName' }})
component.find('form').simulate('submit');
```
And I'm setting up the mock store like this:
```js
const createStore = configureStore([thunk]);

const initialState = {
  user: {
    isLoggedIn: false
  }
};
const store = createStore(initialState);
const component = shallow(<Register store={store} accountType="personal"/>).dive().dive();
```

the register action creator is fired when the form is submitted which should work while configuring the store with the thunk middleware, but I get this error:
```
Error: Actions must be plain objects. Use custom middleware for async actions.
    at dispatch (/home/pendar/avance-account-ui/node_modules/redux-mock-store/lib/index.js:41:19)
    at /home/pendar/avance-account-ui/node_modules/redux-thunk/lib/index.js:14:16
```
Any idea what the problem is?

**Comment by Fazatholomew** [comment]
> I'm having an issue with the thunk middleware not working when I use the mock store through enzyme
> example:
> 
> ```js
> const mapDispatchToProps = dispatch => ({
>   register: data => dispatch(register(data))
>     .then(() => dispatch(login({
>       username: data.email,
>       password: data.password
>     }))),
>   redirectToAccountPage: () => dispatch(push('/my-account'))
> });
> 
> // my test
> register.default.callsFake((data) => {
>   expect(data).toMatchSnapshot();
>   done();
>   return dispatch => dispatch(Promise.resolve({ type: 'register' }));
> });
> component.find('[name="lastName"]')
>   .simulate("change", { target: { value: "Freddy", name: 'lastName' }})
> component.find('[name="firstName"]')
>   .simulate("change", { target: { value: "Fredo", name: 'firstName' }})
> component.find('form').simulate('submit');
> ```
> 
> And I'm setting up the mock store like this:
> 
> ```js
> const createStore = configureStore([thunk]);
> 
> const initialState = {
>   user: {
>     isLoggedIn: false
>   }
> };
> const store = createStore(initialState);
> const component = shallow(<Register store={store} accountType="personal"/>).dive().dive();
> ```
> 
> the register action creator is fired when the form is submitted which should work while configuring the store with the thunk middleware, but I get this error:
> 
> ```
> Error: Actions must be plain objects. Use custom middleware for async actions.
>     at dispatch (/home/pendar/avance-account-ui/node_modules/redux-mock-store/lib/index.js:41:19)
>     at /home/pendar/avance-account-ui/node_modules/redux-thunk/lib/index.js:14:16
> ```
> Any idea what the problem is?

I experience the same. When testing my action with jest.

**Comment by saulwiggin** [comment]
I'm getting a similiar error with jest testing of mockStore 
    Actions must be plain objects. Use custom middleware for async actions.

      54 |     const finalState = { 'componentUnmounted': true};
      55 |     const store = mockStore( initialState );
    > 56 |     store.dispatch(action.DASHBOARD_MOUNTED).then(() => {
         |           ^
      57 |       expect(store.getActions()).toEqual(finalState);
      58 |     });
      59 |   });

**Comment by MuFa117** [comment]
Got into the same issue, for me solution was to follow `redux-mock-store` Async actions documentation: https://github.com/reduxjs/redux-mock-store#asynchronous-actions

![image](https://user-images.githubusercontent.com/9370635/79140008-5184c700-7d85-11ea-8098-ee7e01bf9c18.png)

Bottom line, to **add thunk when configuring mock store for tests.**

**Comment by jkepps** [comment]
I'm experiencing a similar issue while trying to use `renderHook` from `@testing-library/react-hooks`
```ts
  const mockStore = configureStore([thunk])
  const store = mockStore(initialState)
  const result = renderHook(() => hook(...hookArgs), {
    wrapper: ({ children }) => <Provider store={store}>{children}</Provider>,
    ...config,
  })
```
