### ISSUE TITLE
getActions() returns undefined which results in TypeError

### ISSUE THREAD

**Issue by sharq1** [reduxjs/redux-mock-store#44]
Here's my test:

```
  it('should save entry', () => {
    const expectedActions = [
      {type: ENTRY_SAVE_REQUEST},
      {type: ENTRY_SAVE_SUCCESS},
      {type: SYNC_STARTED},
    ];

    // const store = mockStore({}, expectedActions)
    // return store.dispatch(actions.saveEntry())
    const store = mockStore({})
    store.dispatch(actions.saveEntry())
    let retActions = store.getActions()
    expect(retActions).toEqual(expectedActions) // exception thrown here
  })
```

Also tried the old syntax (commented out) but it passes every time, no matter if expected actions are correct or not.

Packages I'm using:

```
babel-jest@12.1.0
jest-cli@12.1.1
redux-mock-store@1.1.0
```

The full error:

```
  - Cannot read property 'toObject' of undefined }) ] to equal [ Object({ type: 'ENTRY_SAVE_REQUEST' }), Object({ type: 'ENTRY_SAVE_SUCCESS' }), Object({ type: 'SYNC_STARTED' }) ].
        at jasmine.buildExpectationResult (node_modules/jest-jasmine2/src/index.js:80:44)
        at Object.eval (src/reducers/entry/__tests__/entryActions-test.js:86:20)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:35:32)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:40:11)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:40:11)
        at Object.<anonymous> (node_modules/jest-jasmine2/src/jasmine-pit.js:40:11)
        at jasmine2 (node_modules/jest-jasmine2/src/index.js:253:7)
        at Test.run (node_modules/jest-cli/src/Test.js:44:12)
        at handle (node_modules/worker-farm/lib/child/index.js:41:8)
        at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
        at emitTwo (events.js:87:13)
        at process.emit (events.js:172:7)
        at handleMessage (internal/child_process.js:686:10)
        at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by dmitry-zaets** [comment]
Can you please provide full code both files with test and action declaration?
Such case is covered by tests and looks working. Probably you have some error in code.

**Comment by sharq1** [comment]
Here you go:
`/reducers/entry/__tests__/entryActions-test.js`

```
'use strict'

jest.autoMockOff()
jest.mock('../../../lib/sync')
jest.mock('../entryDbActions')

let mockStore = require('../../mocks/Store')

let actions = require('../entryActions')

const {
  ENTRY_SAVE_REQUEST,
  ENTRY_SAVE_SUCCESS,

  SYNC_STARTED,
} = require('../../../lib/constants').default

describe('entryActions', () => {

  it('should save entry', () => {
    const expectedActions = [
      {type: ENTRY_SAVE_REQUEST},
      // {type: 'THIS_SHOULD_NOT_GET_DISPATCHED'},
      {type: ENTRY_SAVE_SUCCESS},
      {type: SYNC_STARTED},
    ]

    // const store = mockStore({}, expectedActions)
    // return store.dispatch(actions.saveEntry())
    const store = mockStore({})
    store.dispatch(actions.saveEntry())
    let retActions = store.getActions()
    expect(retActions).toEqual(expectedActions)
  })

})
```

`/reducers/entry/entryActions.js`

```
'use strict'

const {
  ENTRY_SAVE_REQUEST,
  ENTRY_SAVE_SUCCESS,
  ENTRY_SAVE_FAILURE,
} = require('../../lib/constants').default

import {writeEntry, updateEntry} from './entryDbActions'

import {fullSync} from '../../lib/sync'

export function entrySaveRequest() {
  return {
    type: ENTRY_SAVE_REQUEST,
  }
}
export function entrySaveSuccess() {
  return {
    type: ENTRY_SAVE_SUCCESS,
  }
}
export function entrySaveFailure(error) {
  return {
    type: ENTRY_SAVE_FAILURE,
    payload: error,
  }
}

export function saveEntry() {
  return (dispatch, getState) => {
    dispatch(entrySaveRequest())
    try {
      let stateEntry = getState().entry.toObject()
      if (stateEntry.id) {
        // Update
        updateEntry(stateEntry)
      } else {
        // Create
        let user_id = getState().profile.form.originalProfile.objectId
        writeEntry(stateEntry, user_id)
      }
      dispatch(entrySaveSuccess())
      dispatch(fullSync())
    } catch (e) {
      console.log('Error saving entry = ', e)
      dispatch(entrySaveFailure(e))
    }
  }
}
```

**Comment by dmitry-zaets** [comment]
Your error ocures here `getState().entry.toObject()`
You are setting state here as empty object `mockStore({})` and trying to access `entry` which is undefined property. Same problem is here: `getState().profile.form.originalProfile.objectId`

You should build your initial state when you create mockStore. Something like:

``` javascript
const initialState = { entry: {} };
mockStore({})
```

**Comment by dmitry-zaets** [comment]
That's why we have initial store registration in redux-actions-assertions. You can do something similar, you can just create initial state, based on your reducers, and use it. You can check [example here](https://github.com/dmitry-zaets/redux-actions-assertions/blob/master/src/initialState.js#L14-L16).

**Comment by sharq1** [comment]
Thank you @dmitry-zaets! This was it, although old method `mockStore(storeInitialState, expectedActions)` still gives false positives, which bothers me a bit, as I have old tests using this syntax, but I'll just rewrite them.

The other thing is exception reporting, which is not very clear - not truncated message and line number would be very useful!
`- Cannot read property 'toObject' of undefined }) ] to equal [ Object({ type: 'ENTRY_SAVE_REQUEST' }), ...`

Otherwise this solves the issue for me, so you might want to start new issue(s) if you'd like, I'm closing this one.

**Comment by dmitry-zaets** [comment]
@sharq1 you are welcome!

**Comment by mqliutie** [comment]
@dmitry-zaets  
Hello , I meet a question that `TypeError: Cannot read property 'type' of undefined in reducer
`
And in `xx.spec.js` I can get action correctly

In  the reducer I console.log(action) it is object like 
```
{ type: '@@redux/INIT' }
{ type: '@@redux/PROBE_UNKNOWN_ACTION_y.e.o.g.p' }
```

Why the type isn't i have set?
and why there is TypeError? the object has `type` property why there is an error?

Thank you
