### ISSUE TITLE
testing redux-saga with redux-mock-store

### ISSUE THREAD

**Issue by dagda1** [reduxjs/redux-mock-store#59]
I am trying to write a test using redux-saga and redux-mock-store:

Below is my test:

``` js
    import { describe, before, after, it } from 'mocha';
    import { assert, expect } from 'chai';

    import configureMockStore from 'redux-mock-store';

    import { applyMiddleware, compose } from 'redux';

    import createSagaMiddleware from 'redux-saga';

    import fetch from 'isomorphic-fetch';
    import fetchMock from 'fetch-mock';

    import reducer from '../app/reducers';

    import * as actions from '../app/actions/winratio-actions';

    import rootSaga from '../app/sagas';

    const sagaMiddleware = createSagaMiddleware();

    const mockStore = configureMockStore(
      reducer,
      compose(
        applyMiddleware(sagaMiddleware)
      ));


    describe('fetch results', () => {
      after(() => {
        fetchMock.restore();
      });

      it("should call failure action", () => {
        fetchMock.mock('http://localhost:4040/api/results', 501);

        const store = mockStore({});

        store.runSaga = sagaMiddleware.run;

        store.runSaga(rootSaga);

        store.dispatch(actions.loadResultsPage());

        //expect(store).to.not.be.null;
      });
    });
```

But I get the following error message:

> ```
> fetch results should call failure action:
>      TypeError: middleware is not a function
>       at node_modules/redux/lib/applyMiddleware.js:49:16
>       at Array.map (native)
>       at node_modules/redux/lib/applyMiddleware.js:48:27
>       at mockStore (node_modules/redux-mock-store/lib/index.js:70:12)
>       at Context.<anonymous> (results-test.js:36:19)
> ```

The only examples I can find online use redux-thunk:

```
      const middlewares = [ thunk ];
      const mockStore = configureMockStore(middlewares);
```

How do I configure the mock store to use redux-saga?

**Comment by arnaudbenard** [comment]
I don't know, I have never used `redux-saga`. Have you tried only passing the middleware to `configureMockStore`

``` js
const mockStore = configureMockStore([sagaMiddleware]);
```

**Comment by dmitry-zaets** [comment]
@dagda1 Any update on this?
If needed - I can take a look and create an example of testing redux-saga with mock-store.

**Comment by lnhrdt** [comment]
@dmitry-zaets I don't know if @dagda1 ever got it worked out, but I'm also having issues getting this combination (jest, redux-saga, redux-mock-store) to work. Here's my test:

``` es6
jest.unmock('redux');
jest.unmock('redux-saga');
jest.unmock('redux-mock-store');
jest.unmock('nock');
jest.unmock('../saga');
jest.unmock('../actions');

import {applyMiddleware} from 'redux'
import createSagaMiddleware from 'redux-saga'
import configureMockStore from 'redux-mock-store';
import nock from 'nock';
import eventSaga from '../saga';
import actions from '../actions';

describe('eventSaga', () => {
    afterEach(() => {
        nock.cleanAll();
    });

    describe('when EVENT_FETCH_REQUESTED is dispatched', () => {

        describe('when the event exists', () => {

            beforeEach(() => {
                nock('http://example.com/')
                    .get('/api/events/1')
                    .reply(200, {name: 'name'});
            });

            it('dispatches EVENT_FETCH_SUCCEEDED with the response', () => {
                const sagaMiddleware = createSagaMiddleware();
                const mockStore = configureMockStore([applyMiddleware(sagaMiddleware)]);
                sagaMiddleware.run(eventSaga);

                const expectedActions = [
                    {type: actions.eventFetchSucceeded, event: {name: 'name'}}
                ];

                return mockStore.dispatch({type: actions.eventFetchRequested, id: '1'})
                    .then(() => {
                        expect(mockStore.getActions()).toEqual(expectedActions)
                    });
            });
        });
    });
});
```

I get this error:

```
Before running a Saga, you must mount the Saga middleware on the Store using applyMiddleware
```

But I am using `applyMiddleware`. When I remove out `sagaMiddleware.run(eventSaga);` and rerun the test I get this error:

```
TypeError: mockStore.dispatch is not a function
```

I'm new to using redux-mock-store and saw this issue so I thought I'd ask for help navigating this. Any ideas?

**Comment by wendevlin** [comment]
Hello guys,
@lnhrdt 

you forgot to add `const store = mockStore({}); 
`

```
it('dispatches EVENT_FETCH_SUCCEEDED with the response', () => {
                const sagaMiddleware = createSagaMiddleware();
                const mockStore = configureMockStore([applyMiddleware(sagaMiddleware)]);
                sagaMiddleware.run(eventSaga);

                const expectedActions = [
                    {type: actions.eventFetchSucceeded, event: {name: 'name'}}
                ];

                const store = mockStore({});

                return store.dispatch({type: actions.eventFetchRequested, id: '1'})
                    .then(() => {
                        expect(store.getActions()).toEqual(expectedActions)
                    });
            });
```

**Comment by ly710** [comment]
`import configureMockStore from 'redux-mock-store'
import createSagaMiddleware, { takeEvery }  from 'dva/saga';
import { applyMiddleware } from 'redux';
import user from './user';

describe('model user', () => {
    it('test', () => {
        const mySaga = function* () {
            yield* takeEvery('login', user.effects.login);
        };

        const sagaMiddleware = createSagaMiddleware();

        const mockStore = configureMockStore([applyMiddleware(sagaMiddleware)]);
        sagaMiddleware.run(mySaga);

        const store = mockStore({});

        console.log(store);
    })
})`

didn't work

get this error
`uncaught at check Before running a Saga, you must mount the Saga middleware on the Store using applyMiddleware`

**Comment by pierluigi** [comment]
@masterwendu and @lnhrdt 
the 
```
const mockStore = configureMockStore([applyMiddleware(sagaMiddleware)]);
```

should be

```
const mockStore = configureMockStore([sagaMiddleware]);
```

However I'm still struggling to figure out how to also pass reducers to the configureMockStore. I think in  my case I'm trying to write integration tests instead of unit tests, which are supposed to happen in isolation.

**Comment by johngrimes** [comment]
@masterwendu and @lnhrdt This does not work for me either.

This code results in the following error:

```
TypeError: store.dispatch(...).then is not a function
```

This is because store.dispatch returns a plain action when given one.

I really just want to wait for the dispatch to emit any actions, then test if the actions match a snapshot. Any ideas on how to do this?

Right now I am stuck with using a delay (which is bad, because it is slow and flaky), or not testing sagas at all.

**Comment by wendevlin** [comment]
Hi @johngrimes,

You are using redux-saga?
The generator functions and yields are very helpful for testen.

You don't have to wait until anything finished, you run saga.next([here you can add optionally mocked data])

and it runs until the next yield.

Maybe share your specific code, then I can help you better.

Best regards
Wendelin

**Comment by francoiscabrol** [comment]
yes you can write unit tests for sagas using the generators methods (.next()) but it is not the same thing than writing integration tests like you can do by mocking the store. The problem with the saga unit tests is that the tests just re-implement the saga itself and test more its implementation than the behaviours.
I have the same issue with 
```
TypeError: store.dispatch(...).then is not a function
```
The reason is because my action creator return just an object action `{type: MySagaType}` as a regular saga actionCreator and not a promise like an action creators for redux-thunk does.

We would have to find a way to wait for the end of the sagas execution before executing the assertion. Maybe if we can execute a callback when a pre-defined amount of action was dispatched it would be enough. We would also need a timeout to fail the test if no action are dispatched.

**Comment by francoiscabrol** [comment]
I found a solution that works for me.

```javascript
//------------- the saga ----------------
function* fetchSaga(action) {
   try {
      yield put({type: "FETCH_SUCCEEDED", data: "data"});
   } catch (e) {
      yield put({type: "FETCH_FAILED", message: e.message});
   }
}

function* watchers() {
  yield takeEvery("FETCH", fetchSaga);
}

// -------------- the test -----------------
const sagaMiddleware = createSagaMiddleware();
const mockStore = configureStore([sagaMiddleware]);

describe('the sagas', () => {
  it('should execute YOUR_SAGA', (done) => {
    const store = mockStore({});
    sagaMiddleware.run(watchers); // has to be executed after the mockStore() call

    const expectedActions = [
       { "type": "FETCH" },
       { "type": "FETCH_SUCCEEDED", data: "data"}
    ];

    store.subscribe(() => {
      const actions = store.getActions();
      if (actions.length >= expectedActions.length){
        expect(actions).toEqual(expectedActions);
        done();
      }
    });

    // Return the promise
    store.dispatch({ type: "FETCH" });
  });
});
```

**Comment by tiendv89** [comment]
@francoiscabrol 

I met this error: `Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL`

Removing done also removes the error but duplicates the test (the second one also has time-out problem.

Do you have any insights?

Thanks a lot

**Comment by tiendv89** [comment]
So it should be 
<
store.subscribe(() => {
            const actions = store.getActions();
            if (actions.length >= expectedActions.length) {
                expect(actions).toEqual(expectedActions);
            }
        })();
>

**Comment by tiendv89** [comment]
Actually we can do this:
`
sagaMiddleware.run(fetchCategoryList).done.then(() => {
            const actions = store.getActions();
            expect(actions).toMatchSnapshot();
        });
`

**Comment by francoiscabrol** [comment]
I think I was not clear about this line `sagaMiddleware.run(mySaga)` in my example. I actually run the generator that is going to register my saga but my saga is executed only when the action is dispatched by the line `store.dispatch(actions.execute_your_saga());`. Maybe this would solved the issue you had with my snippet. But your way to run the saga is also a valid solution that I will try.

I have updated my previous example.

**Comment by zsid** [comment]
For anyone else coming to this thread, this is what worked for me using `redux-mock-store`, `jest` and `redux-saga`

### Saga
```

function* loginUser() {
  try {
    const someData = yield select(state => state.someData);
    const { data: user } = yield call(api.request, { url: 'url' });
    yield put({ type: 'USER', payload: user });
    const { data: userProfile } = yield call(api.request, {
      url: `/profile/${user}/${someData}`,
    });
    yield put({ type: 'USER_PROFILE', payload: userProfile });
    yield put({ type: 'USER_LOGGED_IN' });
  } catch (e) {
    yield put({ type: 'ERROR' });
  }
}

export function* watchLoginUser() {
  yield takeEvery('LOGIN_USER', loginUser);
}
```

### Test

```
  describe('loginUser', () => {
    it('should login user successfully', async () => {
      const request = jest
        .spyOn(api, 'request')
        .mockImplementationOnce(() => Promise.resolve({ data: 'user' }))
        .mockImplementationOnce(() => Promise.resolve({ data: 'userProfile' }));
      const saga = createSagaMiddleware();
      const state = {
        someData: 'one',
      };
      const store = configureMockStore([saga])(state);
      saga.run(watchLoginUser);
      store.dispatch({ type: 'LOGIN_USER' });
      await Promise.resolve();
      expect(request).toHaveBeenCalledTimes(2);
      expect(request.mock.calls[0][0]).toEqual({ url: 'url' }); // first argument
      // expect(request.mock.calls[0][1]).toEqual(second argument); if there is a second argument
      expect(request.mock.calls[1][0]).toEqual({ url: '/profile/user/one' }); // second api call.
      expect(store.getActions()).toEqual([
        { type: 'LOGIN_USER' },
        { type: 'USER', payload: 'user' },
        { payload: 'userProfile', type: 'USER_PROFILE' },
        { type: 'USER_LOGGED_IN' },
      ]);
      request.mockRestore();
    });
  });
```

**Comment by tuzmusic** [comment]
@francoiscabrol I love the general setup of your code but I'm having a problem.

My saga is watching for `LOGIN_START`, `LOGIN_SUCCESS`, and `LOGIN_FAILURE`. My tests are receiving all three! (although the payload delivered with `LOGIN_SUCCESS` is incorrect, but that's probably a problem with my code under test.)

Adding to that, my test is being *marked* as passing, but there are at least two failures listed below the list of tests, and then the summary at the bottom says that the tests all passed!

Stranger still, while the first failure makes sense (it's about the payload for `LOGIN_SUCCESS` being wrong as I mentioned before, and it's represented with an `-Expected/+Received` explanation),  the next time the subscription is hit, *my actual code* throws the error ` { Error: expect(received).toEqual(expected) // deep equality`. 

I suppose it's possible that *all* these problems are caused by my failing code, but I don't think so.

## Edit/Update:
I've realized that the problem with my code is that I'm not passing any credentials to my `loginSaga`, which not only has everything not work (obviously) but first causes the axios mock matcher to not be matched. When I temporarily changed the matcher to `.onGet(ApiUrls.login) //, { params: success.creds })`, the `LOGIN_SUCCESS` actions carried the correct payload, and my code worked.

**However**, it was still ending with a `LOGIN_FAILURE` that said `"done is not defined",`. When I delete the `done()` call from your code, my tests actually pass (although they're obviously wrong, with that change to the axios mock).

So, there is still some issue with that `done()` code, as well as the fact that there are failure descriptions *and* "tests passed" indications, that are of concern. So I'm leaving my code below.

(But, all in all, way to figure this whole thing out! :))

### code
```js
export async function loginWithApi(creds) {
  try {
    const res = await axios.get(ApiUrls.login, { params: creds });
    if (res.data.data) {
      return res.data;
    } else if (res.data.code) {
      return Error(res.data.code.titleize());
    } // else, it should be an actual error
  } catch (err) {
    return err;
  }
}

export function* loginSaga({ username, password }) {
  try {
    const res = yield call(loginWithApi, { username, password });
    // console.log(res);
    yield put({ type: "LOGIN_SUCCESS", user: res.data }); // not sure we NEED any user data
  } catch (error) {
    console.log("ERROR FROM loginSaga CODE", error);
    yield put({ type: "LOGIN_FAILURE", error });
  }
}

export function* watchLogin() {
  yield takeEvery("LOGIN_START", loginSaga);
}
...
export default function* authSaga() {
  yield all([watchLogin(), watchLogout(), watchRegister()]);
}
```

### tests
```js
describe("reducer integration", () => {
  const sagaMiddleware = createSagaMiddleware();
  const mockStore = configureMockStore([sagaMiddleware]);
  const store = mockStore({});
  sagaMiddleware.run(authSaga);

  let mock = new MockAdapter(axios);
  beforeAll(() => {
    mock
      .onGet(ApiUrls.login, { params: success.creds })
      .reply(200, loginResponse.success)
      .onGet(ApiUrls.login, { params: badUser.creds })
      .reply(200, loginResponse.invalidUsername)
      .onGet(ApiUrls.login, { params: badPw.creds })
      .reply(200, loginResponse.incorrectPassword);
  });
  afterAll(() => {
    mock.restore();
  });

  it("kicks off the login process", () => {
    const expectedActions = [
      { type: "LOGIN_START" },
      { type: "LOGIN_SUCCESS", user: loginResponse.success.data }
    ];
    const expectedTypes = expectedActions.map(a => a.type);

    store.subscribe(() => {
      const actions = store.getActions();
      if (actions.length >= expectedActions.length) {
        expect(actions).toEqual(expectedActions);
        done();
      }
    });
    store.dispatch({ type: "LOGIN_START" });
  });
});
```

### test output
```js
console.log src/redux/actions/authActions.js:89
    ERROR FROM loginSaga CODE { Error: expect(received).toEqual(expected) // deep equality
    
    - Expected
    + Received
    
    @@ -2,19 +2,8 @@
        Object {
          "type": "LOGIN_START",
        },
        Object {
          "type": "LOGIN_SUCCESS",
    -     "user": Object {
    -       "ID": "6",
    -       "display_name": "testuser1",
    -       "user_activation_key": "",
    -       "user_email": "testuser@bolt.com",
    -       "user_login": "testuser1",
    -       "user_nicename": "testuser1",
    -       "user_pass": "$P$BC5js71iidxI4lycappjRcMLowKhld/",
    -       "user_registered": "2019-05-28 20:11:49",
    -       "user_status": "0",
    -       "user_url": "",
    -     },
    +     "user": undefined,
        },
      ]
        // ... big stack trace ...
      matcherResult:
       { actual: [ [Object], [Object] ],
         expected: [ [Object], [Object] ],
         message: [Function],
         name: 'toEqual',
         pass: false } }

  console.log src/redux/actions/authActions.js:90
    ---end of error---

  console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:104
    { Error: expect(received).toEqual(expected) // deep equality
    
    - Expected
    + Received
    
    @@ -2,19 +2,37 @@
        Object {
          "type": "LOGIN_START",
        },
        Object {
          "type": "LOGIN_SUCCESS",
    -     "user": Object {
    -       "ID": "6",
    -       "display_name": "testuser1",
    -       "user_activation_key": "",
    -       "user_email": "testuser@bolt.com",
    -       "user_login": "testuser1",
    -       "user_nicename": "testuser1",
    -       "user_pass": "$P$BC5js71iidxI4lycappjRcMLowKhld/",
    -       "user_registered": "2019-05-28 20:11:49",
    -       "user_status": "0",
    -       "user_url": "",
    +     "user": undefined,
        },
    +   Object {
    +     "error": [Error: expect(received).toEqual(expected) // deep equality
    + 
    + - Expected
    + + Received
    + 
    + @@ -2,19 +2,8 @@
    +     Object {
    +       "type": "LOGIN_START",
    +     },
    +     Object {
    +       "type": "LOGIN_SUCCESS",
    + -     "user": Object {
    + -       "ID": "6",
    + -       "display_name": "testuser1",
    + -       "user_activation_key": "",
    + -       "user_email": "testuser@bolt.com",
    + -       "user_login": "testuser1",
    + -       "user_nicename": "testuser1",
    + -       "user_pass": "$P$BC5js71iidxI4lycappjRcMLowKhld/",
    + -       "user_registered": "2019-05-28 20:11:49",
    + -       "user_status": "0",
    + -       "user_url": "",
    + -     },
    + +     "user": undefined,
    +     },
    +   ]],
    +     "type": "LOGIN_FAILURE",
        },
      ]
        // ... same stack trace as above ...
      matcherResult:
       { actual: [ [Object], [Object], [Object] ],
         expected: [ [Object], [Object] ],
         message: [Function],
         name: 'toEqual',
         pass: false } }

  console.error node_modules/@redux-saga/core/dist/chunk-774a4f38.js:105
    The above error occurred in task loginSaga
        created by takeEvery(LOGIN_START, loginSaga)
        created by authSaga
        created by authSaga
    Tasks cancelled due to error:
    takeEvery(LOGIN_START, loginSaga)

Test Suites: 1 passed, 1 total
Tests:       16 skipped, 1 passed, 17 total
```

**Comment by francoiscabrol** [comment]
Yes my solution was a little bit hack-ish because redux-mock-store was made for redux-thunk and was not design for being used with the sagas. I found recently a library that is very similar but designed for redux-saga called [redux-saga-tester](https://github.com/wix/redux-saga-tester). It's doing the job very well.

**Comment by tuzmusic** [comment]
That definitely looks like a great library! Once I did everything in my code correctly, and removed `done()`, your solution totally works. But redux-saga-tester definitely looks way more concise, I'll have to give it a try!

**Comment by stephanefbouchard** [comment]
@tuzmusic i used your solution and really helper me.
But i needed to fix some stuff to make it work. 

First, we need to add (done) param in the it()

Secondly i needed to add a try catch into the subscribe cause in my case, the error was throw and my saga was catching the error. So to be bullet proof, here is my store.subscribe
```
store.subscribe(() => {
      const actions = store.getActions();
      if (actions.length >= expectedActions.length) {
        try {
          expect(actions).to.eql(expectedActions);
          done();
        } catch (e) {
          done(e);
        }
      }
    });
```

Here is my full exemple based on your exemple : 

exemple.constants.js
```
export const ACTIONS = {
  FETCH: 'EXEMPLE__FETCH',
  FETCH_SUCCESS: 'EXEMPLE__FETCH_SUCCESS',
  FETCH_ERROR: 'EXEMPLE__FETCH_ERROR',
};
```

exemple.actions.js
```
import { createAction } from 'redux-create-action';
import { ACTIONS } from './exemple.constants';

export const fetch = createAction(ACTIONS.FETCH);
export const fetchSuccess = createAction(ACTIONS.FETCH_SUCCESS, 'data');
export const fetchError = createAction(ACTIONS.FETCH_ERROR, 'error');
```

exemple.sagas.js
```
import axios from 'axios';
import { call, put, takeEvery, all } from 'redux-saga/effects';
import { fetchSuccess, fetchError } from './exemple.actions';
import { ACTIONS } from './exemple.constants';

export async function fetchData() {
  return await axios.get('/api/exemple');
}

export function* onFetch() {
  try {
    const { data } = yield call(fetchData);
    yield put(fetchSuccess(data));
  } catch (error) {
    yield put(fetchError(error));
  }
}

export default function* exempleSagas() {
  yield all([
    takeEvery(ACTIONS.FETCH, onFetch),
  ]);
}
```

exemple.test.js
```
import { expect } from 'chai';
import createSagaMiddleware from 'redux-saga';
import configureMockStore from 'redux-mock-store';
import axios from 'axios';
import MockAdapter from 'axios-mock-adapter';
import sagas from './exemple.sagas';
import { ACTIONS } from './exemple.constants';
import { fetch } from './exemple.actions';

const SUCCESS_CODE = 200;
const MOCK_EXEMPLE_API_RESPONSE = { it: "works" };

describe('Exemple service test', () => {
  const sagaMiddleware = createSagaMiddleware();
  const mockStore = configureMockStore([sagaMiddleware]);
  const store = mockStore({});
  sagaMiddleware.run(sagas);

  let mock = new MockAdapter(axios);
  beforeAll(() => {
       mock
         .onGet('/api/exemple')
         .reply(SUCCESS_CODE, MOCK_EXEMPLE_API_RESPONSE);
    });
    afterAll(() => {
      mock.restore();
    });

  it("Fetch a saga test", (done) => {

    const expectedActions = [
      { type: ACTIONS.FETCH },
      { type: ACTIONS.FETCH_SUCCESS, data: MOCK_EXEMPLE_API_RESPONSE },
    ];

    store.subscribe(() => {
      const actions = store.getActions();
      if (actions.length >= expectedActions.length) {
        try {
          expect(actions).to.eql(expectedActions);
          done();
        } catch (e) {
          done(e);
        }
      }
    });
    store.dispatch(fetch());
  });
});
```
