### ISSUE TITLE
TypeError: createStore is not a function

### ISSUE THREAD

**Issue by forgo** [reduxjs/redux-mock-store#84]
My issue is related to:
https://github.com/arnaudbenard/redux-mock-store/issues/59

├── redux@3.6.0
├── redux-mock-store@1.2.1
├── redux-saga@0.14.2

I followed the steps to resolve the same errors experienced by that issue, but the following test still produces an error for me:

```
import createSagaMiddleware from 'redux-saga'
import configureStore from 'redux-mock-store'
import {applyMiddleware} from 'redux'

const testingRoot = "http://localhost:9090";

describe('async actions', () => {

    afterEach(() => {
        nock.cleanAll()
    });

    it('triggers RESPONSE_FILTER_CHANGE_WITH_OPERATORS_SUCCESS when fetchTransmissions completes successfully', () => {

        const sagaMiddleware = createSagaMiddleware();
        const mockStore = configureStore([applyMiddleware(sagaMiddleware)]);
        // sagaMiddleware.run(WaterlevelSagas);

        nock.disableNetConnect();
        const mockedResponse = WaterlevelMockData;
        nock(testingRoot)
            .get(Config.waterlevelCatalog.url.stagedConfig.waterlevelCatalog.url.staged)
            .reply(200, mockedResponse);

        // const fullState = Immutable.fromJS({transmission: {}, operator: {}});
        const expectedActions = [
            {type: FilterActions.REQUEST_FILTER_CHANGE_BY_CATEGORY},
            {type: FilterActions.RESPONSE_FILTER_CHANGE_WITH_OPERATORS_SUCCESS}
        ];

        const store = mockStore({});
        return store.dispatch(FilterActions.requestFilterChangeByCategory(FilterConstants.category.staged))
            .then(() => {
                store.getActions().should.deep.equal(expectedActions)
            });
    })
});
```

The following line:

```
const  store = mockStore({});
```

produces the following error in my test:

```
  1) async actions triggers RESPONSE_FILTER_CHANGE_WITH_OPERATORS_SUCCESS when fetchTransmissions completes successfully:
     TypeError: createStore is not a function
      at node_modules/redux/lib/applyMiddleware.js:38:19
      at node_modules/redux/lib/applyMiddleware.js:51:63
      at mockStore (node_modules/redux-mock-store/lib/index.js:79:12)
      at Context.<anonymous> (src/app/WaterlevelSagas-spec.js:54:23)
```

Any idea on where "createStore" comes into play here and how to resolve this? I haven't used "createStore" anywhere in my test.

**Comment by forgo** [comment]
Turns out it was the "then" on calling store.dispatch wasn't working. I also pulled sagaMiddleware and mockStore assignments to constants outside of the individual tests -- although that is not necessary to fix the problem I was having).

I broke it up like this:

```
 const store = mockStore({});
 store.dispatch(FilterActions.requestFilterChangeByCategory(FilterConstants.category.staged));
 const actions = store.getActions();
 actions.should.deep.equal(expectedActions)
```

**Comment by c10b10** [comment]
@forgo I'm getting the same error, but my context is quite different. I'm trying to implement an integration test, so I need to mount a component, that fetches data from a 3rd party api.

How did you figure out the real issue, because this "createStore missing" error message points me nowhere.

**Comment by c10b10** [comment]
Seems that I didn't need to wrap the saga middleware in 'applyMiddleware', since redux-mock-store does it for me.
